services:
  whoami:
    image: traefik/whoami
    command:
        - --name=whoami-service
        - --port=8080
    networks:
    - net-whoami

  echo:
    image: hashicorp/http-echo
    command:
        - -text=Hello
        - -listen=:8080
    networks:
    - net-echo

  whoami-dynamic:
    image: traefik/whoami
    command:
        - --name=whoami-DYNAMIC-service
        - --port=8080
    labels:
      - "paleo-subdomain=whoami-dynamic"
    networks:
    - net-whoami-dynamic



networks:
  net-whoami:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
  net-echo:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1
  net-whoami-dynamic:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16
         gateway: 10.7.0.1