services:
# This is a sample configuration file for services
- name: "service1"
  # Description of the service
  description: "This is the first service configuration"
  # If the service is enabled
  enabled: true
  # Url to access the service
  subdomain: "demo"
  endpoints:
  - ip: "10.5.0.2"
  - ip: "10.5.0.3"
  - ip: "10.5.0.4"
  - ip: "10.5.0.5"
  - ip: "10.5.0.6"
  port: 8080

# - name: "service2"
#   # Description of the service
#   description: "This is the second service configuration"
#   # If the service is enabled
#   enabled: true
#   # Url to access the service
#   subdomain: "demo2"
#   # Actual IP address for the service
#   ip: "192.168.1.43"
#   # Actual Port number for the service
#   port: 8080
