services:
# This is a sample configuration file for services
- name: "example_service"
  # Description of the service
  description: "An example service configuration"
  # If the service is enabled
  enabled: true
  # Url to access the service
  url: "demo.localhost"
  # Actual IP address for the service
  ip: "192.168.1.43"
  # Actual Port number for the service
  port: 8080

test: "hello"
